// automatically generated by the FlatBuffers compiler, do not modify

package com.google.ar.sceneform.lullmodel;

import java.nio.*;

import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
/**
 * Data type for 2-dimensional vector values to be stored in a VariantDef.
 */
public final class DataVec2 extends Table {
  public static DataVec2 getRootAsDataVec2(ByteBuffer _bb) { return getRootAsDataVec2(_bb, new DataVec2()); }
  public static DataVec2 getRootAsDataVec2(ByteBuffer _bb, DataVec2 obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; vtable_start = bb_pos - bb.getInt(bb_pos); vtable_size = bb.getShort(vtable_start); }
  public DataVec2 __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Vec2 value() { return value(new Vec2()); }
  public Vec2 value(Vec2 obj) { int o = __offset(4); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }

  public static void startDataVec2(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addValue(FlatBufferBuilder builder, int valueOffset) { builder.addStruct(0, valueOffset, 0); }
  public static int endDataVec2(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

