// automatically generated by the FlatBuffers compiler, do not modify

package com.google.ar.sceneform.lullmodel;

import java.nio.*;

import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
/**
 * Data type for arbitrary binary data to be stored in a VariantDef.
 */
public final class DataBytes extends Table {
  public static DataBytes getRootAsDataBytes(ByteBuffer _bb) { return getRootAsDataBytes(_bb, new DataBytes()); }
  public static DataBytes getRootAsDataBytes(ByteBuffer _bb, DataBytes obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; vtable_start = bb_pos - bb.getInt(bb_pos); vtable_size = bb.getShort(vtable_start); }
  public DataBytes __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int value(int j) { int o = __offset(4); return o != 0 ? bb.get(__vector(o) + j * 1) & 0xFF : 0; }
  public int valueLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public ByteBuffer valueAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer valueInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }

  public static int createDataBytes(FlatBufferBuilder builder,
      int valueOffset) {
    builder.startObject(1);
    DataBytes.addValue(builder, valueOffset);
    return DataBytes.endDataBytes(builder);
  }

  public static void startDataBytes(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addValue(FlatBufferBuilder builder, int valueOffset) { builder.addOffset(0, valueOffset, 0); }
  public static int createValueVector(FlatBufferBuilder builder, byte[] data) { return builder.createByteVector(data); }
  public static int createValueVector(FlatBufferBuilder builder, ByteBuffer data) { return builder.createByteVector(data); }
  public static void startValueVector(FlatBufferBuilder builder, int numElems) { builder.startVector(1, numElems, 1); }
  public static int endDataBytes(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

