// automatically generated by the FlatBuffers compiler, do not modify

package com.google.ar.sceneform.lullmodel;

/**
 * Potential Input Devices (matches enum in input_manager.h)
 */
public final class DeviceType {
  private DeviceType() { }
  public static final int Hmd = 0;
  public static final int Mouse = 1;
  public static final int Keyboard = 2;
  public static final int Controller = 3;
  public static final int Controller2 = 4;
  public static final int Hand = 5;

  public static final String[] names = { "Hmd", "Mouse", "Keyboard", "Controller", "Controller2", "Hand", };

  public static String name(int e) { return names[e]; }
}

