// automatically generated by the FlatBuffers compiler, do not modify

package com.google.ar.sceneform.lullmodel;

public final class OptionalBool {
  private OptionalBool() { }
  /**
   * Don't force the value on entity create.
   */
  public static final int Unset = 0;
  /**
   * Force the value to true when created.
   */
  public static final int True = 1;
  /**
   * Force the value to false when created.
   */
  public static final int False = 2;

  public static final String[] names = { "Unset", "True", "False", };

  public static String name(int e) { return names[e]; }
}

