// automatically generated by the FlatBuffers compiler, do not modify

package com.google.ar.sceneform.lullmodel;

import java.nio.*;

import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Recti extends Struct {
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public Recti __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int x() { return bb.getInt(bb_pos + 0); }
  public int y() { return bb.getInt(bb_pos + 4); }
  public int w() { return bb.getInt(bb_pos + 8); }
  public int h() { return bb.getInt(bb_pos + 12); }

  public static int createRecti(FlatBufferBuilder builder, int x, int y, int w, int h) {
    builder.prep(4, 16);
    builder.putInt(h);
    builder.putInt(w);
    builder.putInt(y);
    builder.putInt(x);
    return builder.offset();
  }
}

