// automatically generated by the FlatBuffers compiler, do not modify

package com.google.ar.sceneform.lullmodel;

public final class TextureTargetType {
  private TextureTargetType() { }
  public static final short Standard2d = 0;
  public static final short CubeMap = 1;

  public static final String[] names = { "Standard2d", "CubeMap", };

  public static String name(int e) { return names[e]; }
}

