// automatically generated by the FlatBuffers compiler, do not modify

package com.google.ar.sceneform.lullmodel;

/**
 * Defines the data structure of a single attribute in a vertex. Each type is
 * assumed to be 4-byte aligned.
 */
public final class VertexAttributeType {
  private VertexAttributeType() { }
  public static final int Empty = 0;
  public static final int Scalar1f = 1;
  public static final int Vec2f = 2;
  public static final int Vec3f = 3;
  public static final int Vec4f = 4;
  public static final int Vec2us = 5;
  public static final int Vec4us = 6;
  public static final int Vec4ub = 7;

  public static final String[] names = { "Empty", "Scalar1f", "Vec2f", "Vec3f", "Vec4f", "Vec2us", "Vec4us", "Vec4ub", };

  public static String name(int e) { return names[e]; }
}

